code inspection changes

diff --git a/tasks/get-from-osf b/tasks/get-from-osf
--- a/tasks/get-from-osf
+++ b/tasks/get-from-osf
@@ -9,26 +9,25 @@ osf_projects="${JOBPATH}/osf_projects"
 
 #if no pids provided, error and exit
 if [ ! -e "$osf_projects" ]; then
-    echo "No OSF registration file in job directory"
-    exit 1
+  echo "No OSF registration file in job directory"
+  exit 1
 fi
 
 #Create FROM_OSF dir if needed
 if [ ! -e "${JOBPATH}/FROM_OSF" ]; then
-	mkdir -p "${JOBPATH}/FROM_OSF" 
+  mkdir -p "${JOBPATH}/FROM_OSF" 
 fi
 
 # Iterate through urls
 for this_project  in $(jq --raw-output .project_identifier < $osf_projects ); do
 
- package_name=$( basename $this_project)
+  package_name=$( basename $this_project)
 
- java -jar /opt/batchs/scripts/osf-cli.jar -c /opt/batchs/tasks/osf-cli.conf -n $package_name -o ${JOBPATH}/FROM_OSF $this_project
+  java -jar /opt/batchs/scripts/osf-cli.jar -c /opt/batchs/tasks/osf-cli.conf -n $package_name -o ${JOBPATH}/FROM_OSF $this_project
 
- #if download fails, error and exit
- if [ $? -ne 0 ]; then
+  #if download fails, error and exit
+  if [ $? -ne 0 ]; then
     echo "OSF-CLI returns $?"
     exit 1
- fi
-
+  fi
 done
