code inspection change

diff --git a/tasks/osf-to-rof b/tasks/osf-to-rof
--- a/tasks/osf-to-rof
+++ b/tasks/osf-to-rof
@@ -22,8 +22,8 @@ if !  bundle exec osf_to_rof --project_file $osf_projects --package_dir ${JOBPAT
 fi
 
 #If ROF construction succeeds, copy package file into top workdir, where subsequent ingest steps will expect it.
-if ! cp -f  "${JOBPATH}/FROM_OSF/${project_id}.tar.gz" "${JOBPATH}/${project_id}.tar.gz"; then
-       echo "copy of file ${project_id}.tar.gz"
+if ! mv "${JOBPATH}/FROM_OSF/${project_id}.tar.gz" "${JOBPATH}/${project_id}.tar.gz"; then
+       echo "move of file ${project_id}.tar.gz failed."
        exit 1
 fi
 
